### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by jannikbuscha** [Pratnomenis/znyatok#1]
Hey,

really cool screenshot tool!

I would have some improvement suggestions for this project if you need any.

- screenshot area resizable even after you have already added objects
- set blur strength
- pixelate function (with strength adjustment)
- support multiple monitors
- shortcut for each function (e.g. for arrows = 'a').
- objects selectable to move them (like cloudshot.com)
- offer multiple fonts for text

**Comment by Pratnomenis** [comment]
Thank you very much for feedback. Most of this features are in TODO list :-)
